#apiVersion: infra.sealos.io/v1
#kind: Infra
#metadata:
#  name: infra-apply-test
#spec:
#  ssh:
#    user: ec2-user
#    passwd: "123456"
#    pk: /root/hurz_key.pem
#    pkname: hurz_key
#    port: 22
#  hosts:
#    - roles: [master] # required
#      count: 1 # Required
#      flavor: "t2.large"
#      image: "ami-05248307900d52e3a"
#    - roles: [ node ] # required
#      count: 1 # Required
#      flavor: "t2.medium"
#      image: "ami-05248307900d52e3a"
#---
apiVersion: cluster.sealos.io/v1
kind: Cluster
metadata:
  name: my-cluster
  annotations:
    sealos.io/sealos/version: "4.1.4-rc1"
spec:
  infra: infra-apply-test
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
