apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpgate.fullname" . }}
  labels:
    {{- include "httpgate.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "httpgate.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
      protocol: TCP
  type: ClusterIP
  {{- if .Values.service.preferSameNode }}
  trafficDistribution: PreferSameNode
  {{- end }}
