---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: billingrecordqueries.account.sealos.io
spec:
  group: account.sealos.io
  names:
    kind: BillingRecordQuery
    listKind: BillingRecordQueryList
    plural: billingrecordqueries
    singular: billingrecordquery
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: BillingRecordQuery is the Schema for the billingrecordqueries
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BillingRecordQuerySpec defines the desired state of BillingRecordQuery
            properties:
              endTime:
                format: date-time
                type: string
              orderID:
                type: string
              page:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                type: integer
              pageSize:
                type: integer
              startTime:
                format: date-time
                type: string
              type:
                type: integer
            required:
            - endTime
            - page
            - pageSize
            - startTime
            - type
            type: object
          status:
            description: BillingRecordQueryStatus defines the observed state of BillingRecordQuery
            properties:
              deductionAmount:
                additionalProperties:
                  format: int64
                  type: integer
                type: object
              item:
                items:
                  description: AccountBalanceSpec defines the desired state of AccountBalance
                  properties:
                    amount:
                      description: TODO will delete field in future Timestamp int64
                        `json:"timestamp,omitempty"`
                      format: int64
                      type: integer
                    costs:
                      additionalProperties:
                        format: int64
                        type: integer
                      type: object
                    details:
                      type: string
                    order_id:
                      type: string
                    owner:
                      type: string
                    time:
                      format: date-time
                      type: string
                    type:
                      type: integer
                  required:
                  - order_id
                  - owner
                  - time
                  - type
                  type: object
                type: array
              pageLength:
                type: integer
              rechargeAmount:
                format: int64
                type: integer
              totalCount:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: integer
            required:
            - pageLength
            - rechargeAmount
            - totalCount
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
