apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job-init.fullname" . }}
  labels:
    {{- include "job-init.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "job-init.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "job-init.serviceAccountName" . }}
      restartPolicy: {{ .Values.restartPolicy }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: job-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: LOCAL_REGION
              value: {{.Values.env.localRegion}}
            - name: DOMAIN
              value: {{.Values.env.domain}}
            - name: GLOBAL_COCKROACH_URI
              value: {{.Values.env.globalCockroachUri}}
            - name: LOCAL_COCKROACH_URI
              value: {{.Values.env.localCockroachUri}}
            - name: PASSWORD_SALT
              value: {{ .Values.env.passwordSalt | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.env.adminPassword | quote }}
            - name: ADMIN_USER_NAME
              value: {{ .Values.env.adminUserName | quote }}
            - name: WORKSPACE_PREFIX
              value: {{ .Values.env.workspacePrefix | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
