apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "job-init.fullname" . }}-cluster-role
  labels:
    {{- include "job-init.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - user.sealos.io
    resources:
      - users
    verbs:
      - create
      - update
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "job-init.fullname" . }}-cluster-role-binding
  labels:
    {{- include "job-init.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "job-init.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "job-init.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
