apiVersion: imagehub.sealos.io/v1
kind: Image
metadata:
  name: lingdie.cert.manager.v1.8.0
spec:
  name: lingdie/cert-manager:v1.8.0
  detail:
    keywords: [ storage ]
    description: Cloud native certificate management. X.509 certificate management for Kubernetes and OpenShift
    icon: https://cert-manager.io/images/cert-manager-logo-icon.svg
    docs: docs
    ID: Unkonw
    arch: Unkonw
    size: 1024000
