# Copyright Â© 2022 sealos.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-cloud
  namespace: sealos-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: cloud@sealos.io
    privateKeySecretRef:
      name: letsencrypt-prod
      # name: letsencrypt-staging
    solvers:
    - selector:
        dnsNames:
        - 'cloud.sealos.io'
        - '*.cloud.sealos.io'
      dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true
            ttl: 600
          # Must using this name, due to some rbac issue.
          # @see: https://github.com/snowdrop/godaddy-webhook/blob/main/deploy/webhook-all.yml#L72
          # @see: https://github.com/cert-manager/cert-manager/issues/3432
          groupName: acme.mycompany.com
          solverName: godaddy

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cloud-sealos-io
  namespace: sealos-system
spec:
  secretName: wildcard-cloud-sealos-io-cert
  renewBefore: 240h
  dnsNames:
  - 'cloud.sealos.io'
  - '*.cloud.sealos.io'
  issuerRef:
    name: cluster-issuer-cloud
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sealos,sealos-system,kubernetes-dashboard,kuboard-v2,terminal-app,redisinsight-service,pgadmin-service,affine-system,ns-[\\-a-z0-9]*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "sealos,sealos-system,kubernetes-dashboard,kuboard-v2,terminal-app,redisinsight-service,pgadmin-service,affine-system,ns-[\\-a-z0-9]*"
