apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "user.fullname" . }}-selfsigned-issuer
  labels:
    control-plane: controller-manager
    {{- include "user.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "user.fullname" . }}-serving-cert
  labels:
    control-plane: controller-manager
    {{- include "user.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "user.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "user.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "user.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
