apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: user-selfsigned-issuer
  labels:
    control-plane: controller-manager
    {{- include "user.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: user-serving-cert
  labels:
    control-plane: controller-manager
    {{- include "user.labels" . | nindent 4 }}
spec:
  dnsNames:
    - user-webhook-service.{{ .Release.Namespace }}.svc
    - user-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: user-selfsigned-issuer
  secretName: user-server-cert