apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: user-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/user-serving-cert
webhooks:
  - name: moperationrequest.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: user-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-user-sealos-io-v1-operationrequest
    failurePolicy: Fail
    rules:
      - apiGroups:
          - user.sealos.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - operationrequests
    sideEffects: None
  - name: muser.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: user-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-user-sealos-io-v1-user
    failurePolicy: Fail
    rules:
      - apiGroups:
          - user.sealos.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - users
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: user-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/user-serving-cert
webhooks:
  - name: voperationrequest.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: user-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-user-sealos-io-v1-operationrequest
    failurePolicy: Fail
    rules:
      - apiGroups:
          - user.sealos.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - operationrequests
    sideEffects: None
  - name: vuser.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: user-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-user-sealos-io-v1-user
    failurePolicy: Fail
    rules:
      - apiGroups:
          - user.sealos.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - users
    sideEffects: None
