{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rauth.fullname" . }}-secret-reader
  labels:
    {{- include "rauth.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rauth.fullname" . }}-secret-reader-binding
  labels:
    {{- include "rauth.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "rauth.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
