# Copyright Â© 2022 sealos.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: infra.sealos.io/v1
kind: Infra
metadata:
  name: xiaohan-test
spec:
  hosts:
    - roles: [ master ]
      count: 1
      flavor: t2.medium
      image: "ami-093d54fcd8afe8208"
      disks:
        - capacity: 40
          volumeType: standard
          type: "data"
        - capacity: 33
          volumeType: gp3
          type: "root"
#        - capacity: 34
#          volumeType: gp3
#          type: "data"
#        - capacity: 35
#          volumeType: gp3
#          type: "data"
    - roles: [ node ]
      count: 1
      flavor: t2.medium
      image: "ami-093d54fcd8afe8208"
      disks:
        - capacity: 11
          volumeType: gp3
          type: "root"
        - capacity: 13
          volumeType: gp3
          type: "data"

