---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: objectstorageusers.objectstorage.sealos.io
spec:
  group: objectstorage.sealos.io
  names:
    kind: ObjectStorageUser
    listKind: ObjectStorageUserList
    plural: objectstorageusers
    singular: objectstorageuser
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: ObjectStorageUser is the Schema for the objectstorageusers API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: ObjectStorageUserSpec defines the desired state of ObjectStorageUser
              properties:
                secretKeyVersion:
                  default: 0
                  format: int64
                  type: integer
              type: object
            status:
              description: ObjectStorageUserStatus defines the observed state of ObjectStorageUser
              properties:
                accessKey:
                  type: string
                external:
                  type: string
                internal:
                  type: string
                objectsCount:
                  format: int64
                  type: integer
                quota:
                  format: int64
                  type: integer
                secretKey:
                  type: string
                secretKeyVersion:
                  default: 0
                  format: int64
                  type: integer
                size:
                  description: unit is byte
                  format: int64
                  type: integer
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
