{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "account.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
    {{- include "account.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: {{ .Values.service.metrics.port }}
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
    {{- include "account.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "account.fullname" . }}-webhook-service
  labels:
    control-plane: controller-manager
    {{- include "account.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.webhook.port }}
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
    {{- include "account.selectorLabels" . | nindent 4 }}
