apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "account.fullname" . }}-serving-cert
  name: {{ include "account.fullname" . }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "account.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-v1-sealos-cloud
    timeoutSeconds: 10
    failurePolicy: Ignore
    name: debt.sealos.io
    namespaceSelector:
      matchExpressions:
        - key: user.sealos.io/owner
          operator: Exists
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - '*'
      - apiGroups:
          - account.sealos.io
        apiVersions:
          - v1
        operations:
          - UPDATE
        resources:
          - payments/status
        scope: '*'
    sideEffects: None
