# permissions for end users to edit operationrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operationrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: user
    app.kubernetes.io/part-of: user
    app.kubernetes.io/managed-by: kustomize
  name: operationrequest-editor-role
rules:
- apiGroups:
  - user.sealos.io
  resources:
  - operationrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - user.sealos.io
  resources:
  - operationrequests/status
  verbs:
  - get
