---
- name: make keepalived config dir
  file: 
      path: /etc/keepalived
      state: directory

- name: start keepalived as static pod
  template: 'src={{ item.src }} dest={{ item.dest }} mode=0644'
  with_items:
     - {src: '/etc/ansible/roles/keepalived/templates/keepalived.conf.j2' , dest: '/etc/keepalived/keepalived.conf'}
     - {src: '/etc/ansible/roles/keepalived/templates/keepalived.yaml.j2' , dest: '/etc/kubernetes/manifests/keepalived.yaml'}

- name: copy check script
  template: 'src={{ item.src }} dest={{ item.dest }} mode=0777'
  with_items:
     - {src: '/etc/ansible/roles/keepalived/templates/check_haproxy.sh.j2' , dest: '/etc/keepalived/check_haproxy.sh'}
