{{ if .Values.rbac.create }}
kind: Role
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sealos-desktop
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["user.sealos.io"]
    resources: ["users"]
    verbs: ["*"]
  - apiGroups: ["user.sealos.io"]
    resources: ["users/status"]
    verbs: ["*"]
  - apiGroups: ["user.sealos.io"]
    resources: ["operationrequests"]
    verbs: ["*"]
  - apiGroups: [ "user.sealos.io" ]
    resources: [ "operationrequests/status" ]
    verbs: [ "*" ]
  {{- if .Values.rbac.rules }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.rbac.rules "context" $ ) | nindent 2 }}
  {{- end }}
{{- end }}
