apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-system-manager-role
rules:
  - apiGroups: ['user.sealos.io']
    resources: ['users']
    verbs: ['list', 'get', 'create', 'update', 'patch', 'watch']
  - apiGroups: ['user.sealos.io']
    resources: ['users/status']
    verbs: ['list', 'get', 'create', 'update', 'patch', 'watch']
  - apiGroups: ['user.sealos.io']
    resources: ['operationrequests', 'deleterequests']
    verbs: ['create', 'get']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: desktop-user-editor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-editor-role
subjects:
  - kind: ServiceAccount
    name: desktop-frontend
    namespace: sealos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: desktop-operationrequest-editor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operationrequest-editor-role
subjects:
  - kind: ServiceAccount
    name: desktop-frontend
    namespace: sealos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: desktop-deleterequest-editor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deleterequest-editor-role
subjects:
  - kind: ServiceAccount
    name: desktop-frontend
    namespace: sealos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: recharge-gift-cm-reader
  namespace: sealos
rules:
  - apiGroups: [''] # "" indicates the core API group
    resources: ['configmaps']
    resourceNames: ['recharge-gift']
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recharge-gift-cm-reader-rolebinding
  namespace: sealos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: recharge-gift-cm-reader
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-editor-role
rules:
  - apiGroups: ['account.sealos.io']
    resources: ['accounts']
    verbs: ['list', 'get', 'create', 'update', 'patch', 'watch']
  - apiGroups: ['notification.sealos.io']
    resources: ['notifications']
    verbs: ['list', 'get', 'create', 'update', 'patch', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: desktop-account-editor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: account-editor-role
subjects:
  - kind: ServiceAccount
    name: desktop-frontend
    namespace: sealos
