apiVersion: v1
kind: Secret
metadata:
  name: {{ include "license-frontend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  mongodb_uri: {{ .Values.licenseConfig.mongodbURI | quote }}
