apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "license-frontend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "license-frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
