{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sshgate.fullname" . }}
  labels:
    {{- include "sshgate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sshgate.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "sshgate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
