apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-hubble-sa
  namespace: hubble-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-hubble-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["hubble-relay-client-certs", "hubble-relay-server-certs"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-hubble-rolebinding
  namespace: hubble-service
subjects:
  - kind: ServiceAccount
    name: service-hubble-sa
    namespace: hubble-service
roleRef:
  kind: ClusterRole
  name: service-hubble-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-hubble
  name: service-hubble-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-hubble
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-hubble
    spec:
      serviceAccountName: service-hubble-sa
      containers:
        - args:
            - --config=/config/config.yml
          command:
            - /manager
          image: ghcr.io/labring/sealos-hubble-service:latest
          imagePullPolicy: Always
          name: service-collector
          ports:
            - containerPort: 8428
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 640Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: service-hubble-config
          name: config-vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-hubble
  name: service-hubble
spec:
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: 8428
  selector:
    app: service-hubble