apiVersion: v1
kind: ConfigMap
metadata:
  name: node-gpu-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-controller.labels" . | nindent 4 }}
data:
  gpu: ""
  alias: ""
  nodeLabel: {{ .Values.gpuLabelMapping | toJson | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-alias
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-controller.labels" . | nindent 4 }}
data:
  {{- range .Values.gpuAlias }}
  {{ .name }}: "{{ .value }}"
  {{- end }}
