# Default values for heartbeat cronjob helm chart

schedule: "0 0 * * *"
activeDeadlineSeconds: 600
backoffLimit: 1

image: ghcr.io/labring/sealos-job-heartbeat-controller:latest
imagePullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "heartbeat"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "heartbeat-cronjob"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: false

securityContext:
  allowPrivilegeEscalation: false

nodeSelector: {}

tolerations: []

affinity: {}
