apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "heartbeat.fullname" . }}-cluster-role
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames: [ "kube-system" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}-cluster-role-binding
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "heartbeat.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "heartbeat.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
