apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terminal.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "terminal.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: 50686b4e.sealos.io
  config.yaml: |
    global:
      cloudDomain: {{ .Values.config.cloudDomain | quote }}
      {{- if .Values.config.cloudPort }}
      cloudPort: {{ .Values.config.cloudPort | quote }}
      {{- end }}
    terminalController:
      ingressTLSSecretName: {{ .Values.config.ingressTLSSecretName | quote }}
