apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terminal.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "terminal.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
