apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desktop.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "desktop.name" . }}
    {{- include "desktop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "desktop.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: {{ include "desktop.name" . }}
        {{- include "desktop.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "desktop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-database
          image: "{{ .Values.image }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              export REGION_DATABASE_URL=$(cat /app/data/config.yaml | awk '/regionalCockroachdbURI:/ {print $2}' | tr -d '"')
              export GLOBAL_DATABASE_URL=$(cat /app/data/config.yaml | awk '/globalCockroachdbURI:/ {print $2}' | tr -d '"')
              prisma migrate deploy --schema /app/desktop/prisma/global/schema.prisma
              prisma migrate deploy --schema /app/desktop/prisma/region/schema.prisma
          volumeMounts:
            - mountPath: /app/data/config.yaml
              name: desktop-frontend-volume
              subPath: config.yaml
      containers:
        - name: {{ include "desktop.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              REGION_DATABASE_URL=$(cat /app/data/config.yaml | awk '/regionalCockroachdbURI:/ {print $2}' | tr -d '"') \
              GLOBAL_DATABASE_URL=$(cat /app/data/config.yaml | awk '/globalCockroachdbURI:/ {print $2}' | tr -d '"') \
              node /app/desktop/server.js
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - mountPath: /app/data/config.yaml
              name: desktop-frontend-volume
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      affinity:
        {{- if .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
        {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - {{ include "desktop.name" . }}
                topologyKey: "kubernetes.io/hostname"
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: desktop-frontend-volume
          configMap:
            name: {{ include "desktop.fullname" . }}-config
