# Copyright Â© 2024 sealos.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: go-1-22-5
  namespace: devbox-system
spec:
  classRef: go
  title: go1.22.5
  description: go1.22.5
  config:
    image: ghcr.io/cbluebird/devbox/go1.22.5:2f4067
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  category:
    - ubuntu
    - go
---
apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: go-1-23-0
  namespace: devbox-system
spec:
  classRef: go
  config:
    image: ghcr.io/labring-actions/devbox/go-1.23.0:409348
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - name: devbox-app-port
        port: 8080
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: go 1.23.0
  version: "1.23.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: gin
  namespace: devbox-system
spec:
  classRef: gin
  title: gin
  description: gin
  config:
    image: ghcr.io/cbluebird/devbox/gin:2f4067
  category:
    - ubuntu
    - go
    - gin
---
apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: spring-boot
  namespace: devbox-system
spec:
  classRef: spring-boot
  title: Spring Boot
  description: Spring Boot
  config:
    image: ghcr.io/cbluebird/devbox/spring-boot:2f4067
  category:
    - ubuntu
    - java
    - spring-boot
