name: 'Github Rebot for issues-translator'
on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
jobs:
  translate:
    permissions:
      contents: read
      issues: write
      discussions: write
      pull-requests: write
      metadata: read
    runs-on: ubuntu-24.04
    steps:
      - uses: usthe/issues-translate-action@v2.7
        with:
          IS_MODIFY_TITLE: true
          BOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_BOT_NOTE: Bot detected the issue body's language is not English, translate it automatically. ğŸ‘¯ğŸ‘­ğŸ»ğŸ§‘â€ğŸ¤â€ğŸ§‘ğŸ‘«ğŸ§‘ğŸ¿â€ğŸ¤â€ğŸ§‘ğŸ»ğŸ‘©ğŸ¾â€ğŸ¤â€ğŸ‘¨ğŸ¿ğŸ‘¬ğŸ¿
