name: Github Rebot for Cherry Pick On Comment
on:
  issue_comment:
    types: [created]
jobs:
  cherry-pick:
    name: Cherry Pick
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/cherry-pick') && github.event.comment.user.login=='sealos-ci-robot'
    runs-on: ubuntu-latest
    steps:
      - name: Write vars
        id: set-target
        run: |
          TARGET_BRANCH=$(jq -r ".comment.body" "$GITHUB_EVENT_PATH" | awk '{ print $2 }'  | tr -d '[:space:]')
          echo "ðŸ¤– says: â€¼ï¸ TARGET_BRANCH is $TARGET_BRANCH"
          echo "target=$TARGET_BRANCH" >> $GITHUB_OUTPUT
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Automatic Cherry Pick
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global user.email "sealos-ci-robot"
          git config --global user.name "sealos-ci-robot@sealos.io"
          bash ./scripts/cherry-pick.sh
      - uses: peter-evans/create-pull-request@v5
        with:
          title: 'docs: Automated CherryPick Update for ${{ steps.set-target.outputs.target }} '
          body: |
            copilot:all

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          commit-message: |
            ðŸ¤– cherry-pick to ${{ steps.set-target.outputs.target }} using robot.
          branch: cherry-pick-${{ steps.set-target.outputs.target }}
          base: ${{ steps.set-target.outputs.target }}
          signoff: true
          delete-branch: true
          token: ${{ secrets.GH_PAT }}
          reviewers: cuisongliu
          committer: sealos-ci-robot <sealos-ci-robot@sealos.io>
          author: sealos-ci-robot <sealos-ci-robot@sealos.io>
