name: Cherry Pick On Comment
on:
  issue_comment:
    types: [created]
jobs:
  echo-event:
    name: Print
    runs-on: ubuntu-latest
    steps: |
      echo "${{github.event.comment.author_association}}"
  cherry-pick:
    name: Cherry Pick
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/cherry-pick')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Cherry Pick
        uses: vendoo/gha-cherry-pick@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}