name: Release Cloud

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for manual release"
        required: false
        default: ""
        type: string
      build_offline_tar_only:
        description: "Build offline tar only"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for manual release"
        required: false
        default: ""
        type: string
      build_offline_tar_only:
        description: "Build offline tar only"
        required: false
        default: false
        type: boolean

env:
  # Common versions
  GO_VERSION: "1.20"
  DEFAULT_OWNER: "labring"

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  release-controllers:
    if: ${{ inputs.build_offline_tar_only == false }}
    uses: ./.github/workflows/controllers.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
    secrets: inherit

  release-frontends:
    if: ${{ inputs.build_offline_tar_only == false }}
    uses: ./.github/workflows/frontends.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
    secrets: inherit

  release-service:
    if: ${{ inputs.build_offline_tar_only == false }}
    uses: ./.github/workflows/services.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
    secrets: inherit

  release-webhook:
    if: ${{ inputs.build_offline_tar_only == false }}
    uses: ./.github/workflows/webhooks.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
    secrets: inherit

  release-cloud:
    if: ${{ inputs.build_offline_tar_only == false }}
    needs:
      - release-controllers
      - release-frontends
      - release-service
      - release-webhook
    uses: ./.github/workflows/cloud.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
      build_from: ${{ inputs.tag }}
    secrets: inherit
