name: Release Cloud

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for manual release"
        required: false
        default: ""
        type: string
      build_offline_tar_only:
        description: "Build offline tar only"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for manual release"
        required: false
        default: ""
        type: string
      build_offline_tar_only:
        description: "Build offline tar only"
        required: false
        default: false
        type: boolean

env:
  # Common versions
  GO_VERSION: "1.20"
  DEFAULT_OWNER: "labring"

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  release-controllers:
    if: ${{ inputs.build_offline_tar_only == false }}
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Cloud Controller Release Workflow(only when tagged)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'controllers.yml',
              ref: "refs/tags/${{ github.ref_name }}",
              inputs: {
                  push_image_tag: "${{ github.ref_name }}",
                  push_image: true
              }
            })
  release-frontends:
    if: ${{ inputs.build_offline_tar_only == false }}
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Cloud Frontends Release Workflow(only when tagged)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'frontends.yml',
              ref: "refs/tags/${{ github.ref_name }}",
              inputs: {
                  push_image_tag: "${{ github.ref_name }}",
                  push_image: true
              }
            })

  release-service:
    if: ${{ inputs.build_offline_tar_only == false }}
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Cloud Services Release Workflow(only when tagged)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'services.yml',
              ref: "refs/tags/${{ github.ref_name }}",
              inputs: {
                  push_image_tag: "${{ github.ref_name }}",
                  push_image: true
              }
            })
  release-webhook:
    if: ${{ inputs.build_offline_tar_only == false }}
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Cloud Services Release Workflow(only when tagged)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'webhooks.yml',
              ref: "refs/tags/${{ github.ref_name }}",
              inputs: {
                  push_image_tag: "${{ github.ref_name }}",
                  push_image: true
              }
            })
  release-cloud:
    if: ${{ inputs.build_offline_tar_only == false }}
    needs:
      - release-controllers
      - release-frontends
      - release-service
    uses: ./.github/workflows/cloud.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
      build_from: ${{ inputs.tag }}
    secrets: inherit
