name: Release Cloud

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for manual release'
        required: false
        default: ''
      build_offline_tar_only:
        description: 'Build offline tar only'
        required: false
        default: false
        type: boolean

env:
  # Common versions
  GO_VERSION: "1.20"
  DEFAULT_OWNER: "labring"

jobs:
  save-sealos:
    uses: ./.github/workflows/import-save-sealos.yml
    with:
      artifact_name: sealos-cloud-release

  release-controllers:
    if: ${{ github.event.inputs.build_offline_tar_only == false }}
    uses: ./.github/workflows/controllers.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  release-frontends:
    if: ${{ github.event.inputs.build_offline_tar_only == false }}
    uses: ./.github/workflows/frontends.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  release-service:
    if: ${{ github.event.inputs.build_offline_tar_only == false }}
    needs:
      - save-sealos
    uses: ./.github/workflows/services.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  release-cloud:
    if: ${{ github.event.inputs.build_offline_tar_only == false }}
    needs:
      - save-sealos
      - release-controllers
      - release-frontends
      - release-service
    uses: ./.github/workflows/cloud.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
      build_from: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  release-amd-offline-tar:
    needs:
      - release-cloud
    runs-on: self-hosted
    env:
      RELEASE_TAG: ${{ github.event.inputs.tag || github.event.release.tag_name }}
      OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download sealos
        uses: actions/download-artifact@v4
        with:
          name: sealos-cloud-release
          path: /tmp/
      - name: Verify sealos
        run: |
          sudo chmod a+x /tmp/sealos
          sudo mv /tmp/sealos /usr/bin/sealos
          sudo sealos version
      - name: Build
        run: |
          export CLOUD_VERSION="$RELEASE_TAG"
          export VERSION="$RELEASE_TAG"
          export ARCH=amd64
          bash ./scripts/cloud/build-offline-tar.sh
      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Cat md5sum
        run: cat ./sealos-cloud.tar.gz.md5
      - name: Upload
        run: |
          ossutil cp ./sealos-cloud.tar.gz "oss://$OSS_BUCKET/cloud/sealos-cloud-$RELEASE_TAG-amd64.tar.gz"
          ossutil cp ./sealos-cloud.tar.gz.md5 "oss://$OSS_BUCKET/cloud/sealos-cloud-$RELEASE_TAG-amd64.tar.gz.md5"

  release-arm-offline-tar:
    needs:
      - release-cloud
    runs-on: self-hosted
    env:
      RELEASE_TAG: ${{ github.event.inputs.tag || github.event.release.tag_name }}
      OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download sealos
        uses: actions/download-artifact@v4
        with:
          name: sealos-cloud-release
          path: /tmp/
      - name: Verify sealos
        run: |
          sudo chmod a+x /tmp/sealos
          sudo mv /tmp/sealos /usr/bin/sealos
          sudo sealos version
      - name: Build
        run: |
          export CLOUD_VERSION="$RELEASE_TAG"
          export VERSION="$RELEASE_TAG"
          export ARCH=arm64
          bash ./scripts/cloud/build-offline-tar.sh
      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Cat md5sum
        run: cat ./sealos-cloud.tar.gz.md5
      - name: Upload
        run: |
          ossutil cp ./sealos-cloud.tar.gz "oss://$OSS_BUCKET/cloud/sealos-cloud-$RELEASE_TAG-arm64.tar.gz"
          ossutil cp ./sealos-cloud.tar.gz.md5 "oss://$OSS_BUCKET/cloud/sealos-cloud-$RELEASE_TAG-arm64.tar.gz.md5"
