name: E2E Apply Test

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  call_ci_workflow:
    uses: ./.github/workflows/ci.yml
    if: ${{ contains(github.event.pull_request.labels.*.name, 'need-e2e-apply-test') }}

  e2e_apply_test:
    needs: [ call_ci_workflow ]
    runs-on: ubuntu-latest
    permissions:
      issues: write
    strategy:
      matrix:
        arch: [ arm64, amd64 ]
    outputs:
      test_result: ${{ steps.apply_test.outputs.test_result }}
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libgpgme-dev libbtrfs-dev libdevmapper-dev

      - name: Checkout code
        uses: actions/checkout@v3
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Download sealos binary
        uses: actions/download-artifact@v3
        with:
          name: sealos-${{ matrix.arch }}
          path: /tmp/sealos/bin/

      - name: Download patch image tar
        uses: actions/download-artifact@v3
        with:
          name: patch-image-${{ matrix.arch }}.tar
          path: /tmp/sealos/images/

      - name: Install ginkgo && Run e2e apply test
        id: apply_test
        shell: bash
        run: |
          set -ex
          gzip /tmp/sealos/images/patch-${{ matrix.arch }}.tar
          wget -qO goNew.tgz https://go.dev/dl/go1.20.linux-amd64.tar.gz && tar -zxf goNew.tgz && rm -rf goNew.tgz
          sudo mkdir -p /tmp/golang && sudo mv go /tmp/golang && sudo mkdir -p /opt/gopath/{bin,src,pkg}
          export GOROOT=/tmp/golang/go && export GOPATH=/opt/gopath
          export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
          sudo SEALOS_E2E_TEST_IMAGE_NAME="hub.sealos.cn/labring/kubernetes:v1.25.6" \
            SEALOS_E2E_TEST_PATCH_IMAGE_TAR="/tmp/sealos/images/patch-${{ matrix.arch }}.tar.gz" \
            SEALOS_E2E_TEST_PATCH_IMAGE_NAME="ghcr.io/labring/sealos-merge-patch:${{ env.GIT_COMMIT_SHORT_SHA }}-${{ matrix.arch }}" \
            SEALOS_E2E_TEST_SEALOS_BIN_PATH="/tmp/sealos/bin/sealos" \
            ALIYUN_ACCESS_KEY_ID="${{ secrets.ALIYUN_ACCESS_KEY_ID }}" \
            ALIYUN_ACCESS_KEY_SECRET="${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}" \
            ALIYUN_RESOURCE_GROUP_ID="${{ secrets.ALIYUN_RESOURCE_GROUP_ID }}" \
            ALIYUN_REGION_ID=cn-hangzhou /tmp/golang/go/bin/go run github.com/onsi/ginkgo/v2/ginkgo -v --focus="apply test" test/e2e/
          echo 'test_result=success' >> "$GITHUB_OUTPUT"
  issue_commit:
    needs: [ e2e_apply_test ]
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ always() && contains(github.event.pull_request.labels.*.name, 'need-e2e-apply-test') }} #success() || failure()
    steps:
      - name: Add comment to PR with test status
        uses: peter-evans/create-or-update-comment@v1
        env:
          TEST_RESULT: ${{ needs.e2e_apply_test.outputs.test_result == 'success' && 'Success ğŸ‰ğŸ‰!' || 'â€¼ï¸ Failure' }}
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          repository: ${{ github.repository }}
          body: |
            ğŸ¤– says: E2E Apply Test Result: ${{ env.TEST_RESULT }} <br/>See: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          token: "${{ secrets.GH_PAT }}"